[package]
org = "example"
name = "ordersvc"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "ordersvc.store"
options.datastore = "inmemory"
filePath = "persist/model.bal"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.6.0"
